<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <artifactId>lutece-global-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>8.0.1</version>
    </parent>	
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece.plugins</groupId>
    <artifactId>library-blobstore</artifactId>
    <packaging>jar</packaging>
    <version>2.0.0-SNAPSHOT</version>
    <name>Lutece blobstore library</name>
    <repositories>
        <repository>
            <id>lutece</id>
            <name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>luteceSnapshot</id>
            <name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>
	
    <dependencies>
        <!-- Commons -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.12.0</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.11.0</version>
        </dependency>
        <!-- Log4j -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <!-- MultipartItem, which replaces the commons-fileupload FileItem this library used to implement -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-core-utils</artifactId>
            <version>1.0.0</version>
            <type>jar</type>
        </dependency>
        <!-- JSON -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.17.2</version>
        </dependency>
    </dependencies>
	
    <properties>
        <componentName>blobstore</componentName>
        <log4j.version>2.17.0</log4j.version>
    </properties>
    <scm>
        <connection>scm:git:https://github.com/lutece-platform/lutece-tech-library-blobstore.git</connection>
        <developerConnection>scm:git:https://github.com/lutece-platform/lutece-tech-library-blobstore.git</developerConnection>
        <url>https://github.com/lutece-platform/lutece-tech-library-blobstore.git</url>
      <tag>HEAD</tag>
  </scm>
</project>
